#!/bin/bash

#echo "Can you make a commit? Well, it depends."
#exit 0

#!/bin/bash

# Exits with non zero status if tests fail or linting errors exist
#num_of_failures=`mocha -R json | grep failures -m 1 | awk '{print $2}' | sed 's/[,]/''/'`

echo "Running pre-commit hook"
npm test
